//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Objects;

namespace MvcApplication2
{
    public partial class EmployeeDirectoryEntities : DbContext
    {
        public EmployeeDirectoryEntities()
            : this(false) { }
    
        public EmployeeDirectoryEntities(bool proxyCreationEnabled)	    
            : base("name=EmployeeDirectoryEntities")
        {
            this.Configuration.ProxyCreationEnabled = proxyCreationEnabled;
        }
    
        public EmployeeDirectoryEntities(string connectionString)
          : this(connectionString, false) { }
    
        public EmployeeDirectoryEntities(string connectionString, bool proxyCreationEnabled)
            : base(connectionString)
        {
            this.Configuration.ProxyCreationEnabled = proxyCreationEnabled;
        }	
    
        public ObjectContext ObjectContext
        {
          get { return ((IObjectContextAdapter)this).ObjectContext; }
        }
    
    	protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    	
        public DbSet<User> Users { get; set; }
    }
}
